apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtle-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        namespace: default

    spec:
      containers:
      - name: nginx
        image: nginx:stable
